### ISSUE TITLE
About us in footer is now missing text

### ISSUE THREAD

**Issue by nathansam** [VallejosGroup/VallejosGroup.github.io#4]
For the footer,  

``` html
Biological Data Science research group <br> MRC Human Genetics Unit
```

Has been replaced with 

             

in 0151f147c516955afe45cdf287fa32d92df3be7a

Meaning we now have the "about us title" in the footer but not any information.

**Comment by Alanocallaghan** [comment]
¯\_(ツ)_/¯

**Comment by nathansam** [comment]
Alternatively titled:
# Hugo broke stuff.

**Comment by Alanocallaghan** [comment]
Seems that way yeah. I installed the snap because I can't be bothered setting up go again

**Comment by Alanocallaghan** [comment]
Not sure what version I had before

**Comment by Alanocallaghan** [comment]
I guess it stops you from getting xssed on your own website or something https://discourse.gohugo.io/t/raw-html-getting-omitted-in-0-60-0/22032

**Comment by nathansam** [comment]
Thanks Alan!

**Comment by Alanocallaghan** [comment]
Thanks for spotting, I guess I need to do more side by side checks
