### ISSUE TITLE
author name format in publications

### ISSUE THREAD

**Issue by catavallejos** [VallejosGroup/VallejosGroup.github.io#42]
currently we have commas to separate name/surname and authors e.g.

*Vallejos, Catalina A, Cheng, Yipeng and Constantine-Cooke, Nathan*

Can we fix this? Ideally, we will have something like

*Catalina A Vallejos, Yipeng Cheng and Nathan Constantine-Cooke*

**Comment by nathansam** [comment]
I have changed the author format. However, as a comma is currently added after all but the last author, we are instead using an Oxford/serial comma, I.E Catalina A Vallejos, Yipeng Cheng, and Nathan Constantine-Cooke. If it is strictly necessary to not have a comma before 'and', I can look at implementing logic for it at some point (If second author, don't append comma after name).

**Comment by catavallejos** [comment]
thanks Nathan! Looks good... no need to make further changes :-)

**Comment by nathansam** [comment]
Thanks 😄
